// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.0
// source: server.proto

package cache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddserviceClient is the client API for Addservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddserviceClient interface {
	Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error)
}

type addserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddserviceClient(cc grpc.ClientConnInterface) AddserviceClient {
	return &addserviceClient{cc}
}

func (c *addserviceClient) Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/cache.Addservice/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddserviceServer is the server API for Addservice service.
// All implementations must embed UnimplementedAddserviceServer
// for forward compatibility
type AddserviceServer interface {
	Add(context.Context, *Req) (*Res, error)
	mustEmbedUnimplementedAddserviceServer()
}

// UnimplementedAddserviceServer must be embedded to have forward compatible implementations.
type UnimplementedAddserviceServer struct {
}

func (UnimplementedAddserviceServer) Add(context.Context, *Req) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAddserviceServer) mustEmbedUnimplementedAddserviceServer() {}

// UnsafeAddserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddserviceServer will
// result in compilation errors.
type UnsafeAddserviceServer interface {
	mustEmbedUnimplementedAddserviceServer()
}

func RegisterAddserviceServer(s grpc.ServiceRegistrar, srv AddserviceServer) {
	s.RegisterService(&Addservice_ServiceDesc, srv)
}

func _Addservice_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddserviceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.Addservice/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddserviceServer).Add(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Addservice_ServiceDesc is the grpc.ServiceDesc for Addservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.Addservice",
	HandlerType: (*AddserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Addservice_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
